config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  
  match '/chef_export_csv', to: 'home#export_to_csv', via: :get, as: :chef_csv
  match '/got_error', to: 'home#error', via: :get, as: :error


  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from SocketError, with: :socket_error

private 
  def socket_error
    flash[:alert] = 'Socket Error, unable to connect to chef server'
    redirect_to error_path
  end
end

app/controllers/home_controller.rb
require 'csv' 

class HomeController < ApplicationController
  before_filter :get_data, only: [ :index ] 

  def index 
  end 
  
  def error
  end 

  def export_to_csv 
    @@data ||= get_data       
    csv_string = CSV.generate do |csv|
      csv << [
              'Role', 'Fqdn', 'Ip', 'Cluster name', 'Shard name',
              'Priority', 'Component to balance', 'Balanced FQDNs'
             ]
      @@data.nodes_by_role.sort.map do |role,nodes|
        nodes.each do |node|
          csv << [
                  role, node.hostname, node.ip, node.cluster_name, 
                  node.shard_name, node.balance_component, node.balanced_fqdns
                 ]
        end
      end
    end    

    headers = {
      type: 'text/csv; charset=iso-8859-1; header=present',
      disposition: "attachment; filename=nodes_#{@@data.env}.csv"
    }

    send_data(csv_string, headers)
  end 

  private 
    def get_data 
      @data = EndPoint.new 
      @data.get_topology
      @@data = @data 
    end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end



end

app/views/home/error.html.erb
<div class="row">
  <div id="breadcrumb" class="col-xs-12">
    <ol class="breadcrumb">
      <li><%= link_to 'Home', root_path %></li>
      <li>Chef API Query</li>
    </ol>
  </div>
</div>


<div id="dashboard-header" class="row">
  <div class="col-xs-10 col-sm-2">

  </div>
</div>

<div class="row-fluid">
  <%= render 'layouts/messages' %>
</div>

app/views/home/index.html.erb
<!--Start Breadcrumb-->
<div class="row">
  <div id="breadcrumb" class="col-xs-12">
    <ol class="breadcrumb">
      <li><%= link_to 'Home', root_path %></li>
      <li>Chef API Query</li>
    </ol>
  </div>
</div>
<!--End Breadcrumb-->
<!--Start Dashboard 1-->
<div id="dashboard-header" class="row">
  <div class="col-xs-10 col-sm-2">
    <h3><%= @data.env %> dashboard</h3>
  </div>
</div>

<!--End Dashboard 1-->
<!--Start Dashboard 2-->

<div class="row-fluid">
  <div id="dashboard_links" class="col-xs-12 col-sm-2 pull-right">
    <ul class="nav nav-pills nav-stacked" data-no-turbolinks>
      <li class="active"><a href="#" class="tab-link" id="overview">Nodes</a></li>
      <li><a href="#" class="tab-link" id="clients">Nodes without role</a></li>
      <li><a href="#" class="tab-link" id="graph">Nodes without env</a></li>
    </ul>
  </div>
  <div id="dashboard_tabs" class="col-xs-12 col-sm-10">
    <!--Start Dashboard Tab 1-->
    <div id="dashboard-overview" class="row" style="visibility: visible; position: relative;">
      <div id="ow-marketplace" class="col-sm-12 col-md-6">
        <div id="ow-setting">
            <%= link_to chef_csv_path, data: { no_turbolink: true } do %>
              <i class="fa fa-download"></i>
            <% end %>
        </div>
        <h4 class="page-header">SUMMARY</h4>
        <table id="ticker-table" class="table m-table table-bordered table-hover table-heading">
          <thead>
            <tr>
              <th>Role</th>
              <th>Fqdn</th>
              <th>Ip</th>
              <th>Cluster name</th>
              <th>Shard name</th>
              <th>Priority </th>
              <th>Component to balance</th>
              <th>Balanced FQDNs</th>
            </tr>
          </thead>
          <tbody>
          <% @data.nodes_by_role.sort.map do |k,v| %>
            <% v.each do |node| %>
            <tr>
              <td class="m-ticker"><%= k.to_s %> </td>
              <td class="m-ticker"><%= node.hostname %></td>
              <td class="m-ticker"><%= node.ip %></td>
              <td class="m-ticker"><%= node.cluster_name %></td>
              <td class="m-ticker"><%= node.shard_name %></td>
              <td class="m-ticker"><%= node.priority %></td>
              <td class="m-ticker"><%= node.balance_component %></td>
              <td class="m-ticker"><%= node.balance_fqdns %></td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <!--End Dashboard Tab 1-->
    <!--Start Dashboard Tab 2-->

    <div id="dashboard-clients" class="row" style="visibility: hidden; position: absolute;">
      <div class="col-sm-12 col-md-6">
        <h4 class="page-header">Nodes without role</h4>
        <table id="ticker-table" class="table m-table table-bordered table-hover table-heading">
          <thead>
            <tr>
              <th>Fqdn</th>
              <th>Ip</th>
            </tr>
          </thead>
          <tbody>
          <% @data.nodes_without_role.each do |node| %>
            <tr>
              <td class="m-ticker"><%= node.hostname %></td>
              <td class="m-ticker"><%= node.ip %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
      <!--End Dashboard Tab 2-->
      <!--Start Dashboard Tab 3-->
      <div id="dashboard-graph" class="row" style="visibility: hidden; position: absolute;" >
        <div class="col-sm-12 col-md-6">
          <h4 class="page-header">Nodes without env</h4>
          <table id="ticker-table" class="table m-table table-bordered table-hover table-heading">
            <thead>
              <tr>
                <th>Fqdn</th>
                <th>Ip</th>
              </tr>
            </thead>
            <tbody>
              <% @data.nodes_without_env.each do |node| %>
                <tr>
                  <td class="m-ticker"><%= node.hostname %></td>
                  <td class="m-ticker"><%= node.ip %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    <!--End Dashboard Tab 3-->
  </div>
  <div class="clearfix"></div>
</div>
<!--End Dashboard 2 -->
<div style="height: 40px;"></div>
<script type="text/javascript">
// Array for random data for Sparkline
var sparkline_arr_1 = SparklineTestData();
var sparkline_arr_2 = SparklineTestData();
var sparkline_arr_3 = SparklineTestData();
$(document).ready(function() {
  // Make all JS-activity for dashboard
  DashboardTabChecker();
  // Load Knob plugin and run callback for draw Knob charts for dashboard(tab-servers)
  LoadKnobScripts(DrawKnobDashboard);
  // Load Sparkline plugin and run callback for draw Sparkline charts for dashboard(top of dashboard + plot in tables)
  LoadSparkLineScript(DrawSparklineDashboard);
  // Load Morris plugin and run callback for draw Morris charts for dashboard
  LoadMorrisScripts(MorrisDashboard);
  // Make beauty hover in table
  $("#ticker-table").beautyHover();
});
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chef Api Query" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chef Api Query" %>">

      <meta charset="utf-8">
      <title>cheF API Query</title>
      <meta name="description" content="description">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" data-turbolinks-track>
      <link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'data-turbolinks-track>
      <link href="plugins/fancybox/jquery.fancybox.css" rel="stylesheet" data-turbolinks-track>
      <link href="plugins/fullcalendar/fullcalendar.css" rel="stylesheet" data-turbolinks-track>
      <link href="plugins/xcharts/xcharts.min.css" rel="stylesheet" data-turbolinks-track>
      <link href="plugins/select2/select2.css" rel="stylesheet" data-turbolinks-track>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
          <script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
          <script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
      <![endif]-->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
 <!--  <body>
    <header>
    </header>
    <main role="main">
    </main>
  </body>
</html> -->

<body>
<!--Start Header-->
<div id="screensaver">
  <canvas id="canvas"></canvas>
  <i class="fa fa-lock" id="screen_unlock"></i>
</div>
<div id="modalbox">
  <div class="devoops-modal">
    <div class="devoops-modal-header">
      <div class="modal-header-name">
        <span>Basic table</span>
      </div>
      <div class="box-icons">
        <a class="close-link">
          <i class="fa fa-times"></i>
        </a>
      </div>
    </div>
    <div class="devoops-modal-inner">
    </div>
    <div class="devoops-modal-bottom">
    </div>
  </div>
</div>
<header class="navbar">
  <div class="container-fluid expanded-panel">
    <div class="row">
      <div id="logo" class="col-xs-12 col-sm-2">
        <%= link_to 'Chef API Query', root_path %>
      </div>
      <div id="top-panel" class="col-xs-12 col-sm-10">
        <div class="row">
          <div class="col-xs-8 col-sm-4" data-no-turbolink>
            <a href="#" class="show-sidebar">
              <i class="fa fa-bars"></i>
            </a>
            <div id="search">
              <input type="text" placeholder="search"/>
              <i class="fa fa-search"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main" class="container-fluid">
  <div class="row">
    <div id="sidebar-left" class="col-xs-2 col-sm-2">
      <ul class="nav main-menu">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-dashboard"></i>
            <span class="hidden-xs">Dashboard</span>
          <% end %>
        </li>
      </ul>
    </div>
    <!--Start Content-->
    <div id="content" class="col-xs-12 col-sm-10">
      <div class="preloader">
        <img src="img/devoops_getdata.gif" class="devoops-getdata" alt="preloader"/>
      </div>
      <%= yield %>
    </div>
    <!--End Content-->
  </div>
</div>
<!--End Container-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="http://code.jquery.com/jquery.js"></script>-->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="plugins/justified-gallery/jquery.justifiedgallery.min.js"></script>
<script src="plugins/tinymce/tinymce.min.js"></script>
<script src="plugins/tinymce/jquery.tinymce.min.js"></script>
<!-- All functions for this theme + document.ready processing -->
</body>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>